{"version":"3.4.1","examples":[{"description":"takes in a number as an argument and returns the sum of that number and 2","full_description":"#plus_two takes in a number as an argument and returns the sum of that number and 2","status":"passed","file_path":"./spec/pry_debugging_spec.rb","line_number":5,"run_time":0.000419,"pending_message":null}],"summary":{"duration":0.000831,"example_count":1,"failure_count":0,"pending_count":0},"summary_line":"1 example, 0 failures"}